_schema: _schema
source: /public/admin
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  public_admin:
    path: public/admin
    name: Public Admin
    icon: public_off
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_noticias:
    path: src/content/noticias
    name: Src Content Noticias
    icon: content_copy
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  .html:
    path:
    glob:
    name:
    singular_name:
    icon: notes
    url:
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: Europe/Madrid
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
