backend:
  name: git-gateway         # Para publicar directamente desde Netlify CMS
  branch: main              # Cambia si tu rama principal es otra (por ejemplo, master)

media_folder: "public/uploads"      # Las imágenes se guardan aquí dentro del proyecto
public_folder: "/uploads"

site_url: "https://tendidodigital.es"
display_url: "https://tendidodigital.es"

collections:
  - name: "noticias"                # nombre interno de la colección
    label: "Noticias"               # nombre visible en el panel del CMS
    folder: "src/noticias"          # carpeta donde se guardan los .md
    create: true                    # permite crear nuevas entradas
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # formato del nombre del archivo
    preview_path: "noticias/{{slug}}"             # cómo se verá la URL final
    editor:
      preview: false                # opcional: quita la vista previa interna

    fields:                         # campos del formulario de cada noticia
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Imagen destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Descripción breve", name: "summary", widget: "text", required: false}
      - {label: "Contenido principal", name: "body", widget: "markdown"}
