backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://tendidodigital.es"
display_url: "https://tendidodigital.es"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor: { preview: false }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
