backend:
  name: git-gateway
  branch: main   # <-- cambie a 'master' si su repo usa master

media_folder: "static/uploads"   # donde se guardan los archivos en el repo
public_folder: "/uploads"        # URL pública para esos archivos

# Opcional: usar editorial workflow (crea ramas PRs para publicar)
# publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"   # cambie según su estructura
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "description", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
